"""empty message

Revision ID: 60f668afadb7
Revises:
Create Date: 2018-05-08 04:24:32.990814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f668afadb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
                    sa.Column('username', sa.VARCHAR(length=80),
                              autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column('name', sa.VARCHAR(length=80),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('username', name='User_pkey'))
    # ### end Alembic commands ###
