"""empty message

Revision ID: f154639fa3ea
Revises:
Create Date: 2018-05-20 00:03:41.568605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f154639fa3ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('File',
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('filetype', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filename')
    )
    op.drop_table('mytable')
    op.add_column('User', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('id', sa.String(length=100), nullable=False))
    op.alter_column('User', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.alter_column('User', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('User', 'id')
    op.drop_column('User', 'email')
    op.create_table('mytable',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mytable_pkey')
    )
    op.drop_table('File')
    # ### end Alembic commands ###
