"""empty message

Revision ID: fcf45bf69059
Revises: cf531953b5aa
Create Date: 2018-05-14 20:35:34.204886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf45bf69059'
down_revision = 'cf531953b5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User',
        sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('User',
        'username',
        existing_type=sa.VARCHAR(length=80),
        nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User',
        'username',
        existing_type=sa.VARCHAR(length=80),
        nullable=False)
    op.drop_column('User', 'id')
    # ### end Alembic commands ###
