"""empty message

Revision ID: 01d6d1e648d1
Revises: 6619326ff408
Create Date: 2018-06-21 18:18:45.544682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d6d1e648d1'
down_revision = '6619326ff408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Badges', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'File', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('User', sa.Column('siteAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'siteAdmin')
    op.drop_constraint(None, 'File', type_='foreignkey')
    op.drop_constraint(None, 'Badges', type_='foreignkey')
    # ### end Alembic commands ###
