"""empty message

Revision ID: 0a6d2e024685
Revises: 6619326ff408
Create Date: 2018-06-19 19:51:17.650316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6d2e024685'
down_revision = '6619326ff408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Badges', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('User', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'created_at')
    op.drop_column('Badges', 'created_at')
    # ### end Alembic commands ###
