"""empty message

Revision ID: 0f541a3193b2
Revises: ba0a1f466b08
Create Date: 2018-06-11 16:45:56.101695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f541a3193b2'
down_revision = 'ba0a1f466b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('one_time_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'one_time_login')
    # ### end Alembic commands ###
