"""empty message

Revision ID: 9f78f55cf7f3
Revises: b6414a3cd355
Create Date: 2018-07-20 16:30:18.437101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f78f55cf7f3'
down_revision = 'b6414a3cd355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('last_login_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'last_login_ip')
    # ### end Alembic commands ###
