"""empty message

Revision ID: b8ee052fd04e
Revises: f19735b3cda3
Create Date: 2018-07-07 21:22:17.612626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ee052fd04e'
down_revision = 'f19735b3cda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Badges', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Badges', 'image_link')
    # ### end Alembic commands ###
