"""empty message

Revision ID: df0350fb6a18
Revises: f82c06cf3a14
Create Date: 2018-07-02 20:47:27.114938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0350fb6a18'
down_revision = 'f82c06cf3a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Roles', sa.Column('isDefault', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Roles', 'isDefault')
    # ### end Alembic commands ###
