"""empty message

Revision ID: efb1c182508b
Revises: 44af135eb41b
Create Date: 2018-08-02 09:20:15.137222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb1c182508b'
down_revision = '44af135eb41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Settings', sa.Column('fromMail', sa.String(), nullable=True))
    op.add_column('Settings', sa.Column('sendGridApiKey', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Settings', 'sendGridApiKey')
    op.drop_column('Settings', 'fromMail')
    # ### end Alembic commands ###
