"""empty message

Revision ID: f9444b3a16b4
Revises: e7e7c9ed6863
Create Date: 2018-07-03 19:07:37.212076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9444b3a16b4'
down_revision = 'e7e7c9ed6863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Permissions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('isUser', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('isSales', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Permissions')
    # ### end Alembic commands ###
