"""empty message

Revision ID: 2780e9c4144f
Revises: 
Create Date: 2018-07-08 10:36:07.658246

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2780e9c4144f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticketInclude', sa.Boolean(), nullable=True),
    sa.Column('paymentInclude', sa.Boolean(), nullable=True),
    sa.Column('donationInclude', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reset Password Token',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SocialContent',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('User',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('photoURL', sa.String(), nullable=True),
    sa.Column('allowed_usage', sa.Integer(), nullable=True),
    sa.Column('ftl', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('siteAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Utilities',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('pricing', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Badges',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('csv', sa.String(length=100), nullable=False),
    sa.Column('text_color', sa.String(length=100), nullable=False),
    sa.Column('badge_size', sa.String(length=100), nullable=False),
    sa.Column('download_link', sa.String(), nullable=True),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('File',
    sa.Column('id', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('filetype', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filename')
    )
    op.create_table('Permissions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('isUser', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('isSales', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Permissions')
    op.drop_table('File')
    op.drop_table('Badges')
    op.drop_table('Utilities')
    op.drop_table('User')
    op.drop_table('SocialContent')
    op.drop_table('Reset Password Token')
    op.drop_table('Modules')
    # ### end Alembic commands ###
