"""empty message

Revision ID: 4b938f321f0d
Revises: 
Create Date: 2018-05-22 02:39:20.780946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b938f321f0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Badges',
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=100), nullable=False),
    sa.Column('background_image', sa.String(length=100), nullable=False),
    sa.Column('csv', sa.String(length=100), nullable=False),
    sa.Column('font', sa.String(length=100), nullable=False),
    sa.Column('font_size', sa.String(length=100), nullable=False),
    sa.Column('font_color', sa.String(length=100), nullable=False),
    sa.Column('badge_size', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('File',
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('filetype', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filename')
    )
    op.add_column('User', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('id', sa.String(length=100), nullable=False))
    op.alter_column('User', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.alter_column('User', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('User', 'id')
    op.drop_column('User', 'email')
    op.drop_table('File')
    op.drop_table('Badges')
    # ### end Alembic commands ###
