"""empty message

Revision ID: 90bcaf09b4eb
Revises: cb411916be68
Create Date: 2018-07-19 14:22:32.724355

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '90bcaf09b4eb'
down_revision = 'cb411916be68'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Settings',
    sa.Column('id', sa.DateTime(), nullable=False),
    sa.Column('appEnvironment', sa.Integer(), nullable=False),
    sa.Column('appName', sa.String(), nullable=False),
    sa.Column('secretKey', sa.String(), nullable=False),
    sa.Column('firebaseStorageBucket', sa.String(), nullable=False),
    sa.Column('firebaseDatabaseURL', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Settings')
    # ### end Alembic commands ###
