"""empty message

Revision ID: cb411916be68
Revises: 2780e9c4144f
Create Date: 2018-07-11 21:40:44.243565

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cb411916be68'
down_revision = '2780e9c4144f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Badges', sa.Column('badge_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Badges', 'badge_name')
    # ### end Alembic commands ###
