"""empty message

Revision ID: cec42e929259
Revises:
Create Date: 2018-05-22 01:49:05.362876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec42e929259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Badges',
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('csv', sa.String(length=100), nullable=False),
    sa.Column('badge_id', sa.String(length=100), nullable=False),
    sa.Column('text_color', sa.String(length=100), nullable=False),
    sa.Column('badge_size', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('badge_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Badges')
    # ### end Alembic commands ###
